In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Data_id(in).csv')

In [ ]:
df

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,4996,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,728x90,medianet,...,363.0,0.05828,0.05828,0.05828,0.058280,NaN,NaN,NaN,NaN,NaN
4997,4997,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_22,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,4998,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_27,310x260,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,4999,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_33,728x90,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              5000 non-null   int64
 1   date_hour               5000 non-null   object
 2   client                  5000 non-null   object
 3   device_type             5000 non-null   object
 4   time_zone               5000 non-null   object
 5   os_name                 5000 non-null   object
 6   browser_name            5000 non-null   object
 7   ad_unit                 5000 non-null   object
 8   size                    5000 non-null   object
 9   bidder                  5000 non-null   object
 10  bid_range               5000 non-null   object
 11  media_type              5000 non-null   object
 12  request_count           5000 non-null   int64
 13  response_count          5000 non-null   int64
 14  prebid_win_count        1167 non-null   float64
 15  win_count               186 non-null    float64
 16  sum_bid                 3790 non-null   float64
 17  sum_time_to_respond     3790 non-null   float64
 18  median                  1760 non-null   float64
 19  min_bid                 3790 non-null   float64
 20  max_bid                 3790 non-null   float64
 21  avg_bid                 3790 non-null   float64
 22  sum_2nd_highest_bid     734 non-null    float64
 23  sum_prebid_winning_bid  1167 non-null   float64
 24  sum_winning_bid         186 non-null    float64
 25  sum_nobid               0 non-null      float64
 26  sum_timeout             0 non-null      float64
dtypes: float64(13), int64(3), object(11)
memory usage: 1.0+ MB

In [ ]:
df['bidder'].unique()

array(['onemobile', 'rhythmone', 'undertone', ' ', 'pulsepoint',
       'pubmatic', 'triplelift', 'sharethrough', 'ix', 'medianet',
       'appnexus', '33across', 'openx', 'emx_digital', 'rubicon',
       'criteo', 'sovrn', 'teads'], dtype=object)

In [ ]:
df['bidder'].replace(' ', 'unknown', inplace = True)

/tmp/ipython-input-1186974703.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bidder'].replace(' ', 'unknown', inplace = True)

In [ ]:
df['prebid_win_count'].fillna(0)

0       1.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
4995    0.0
4996    0.0
4997    0.0
4998    0.0
4999    0.0
Name: prebid_win_count, Length: 5000, dtype: float64

In [ ]:
df_summary = df.groupby('bidder').agg(
    total_bids=('response_count','sum'),
    total_win=('prebid_win_count', 'sum')
).reset_index()

In [ ]:
df_summary

          bidder  total_bids  total_win
0       33across         886      136.0
1       appnexus         830      175.0
2         criteo        3181      587.0
3    emx_digital         393       56.0
4             ix        3051      184.0
5       medianet        2556      253.0
6      onemobile        2726      759.0
7          openx        1165       86.0
8       pubmatic        2335      255.0
9     pulsepoint         191       71.0
10     rhythmone         655      160.0
11       rubicon         582       33.0
12  sharethrough         332      104.0
13         sovrn         358       14.0
14         teads         700      323.0
15    triplelift        1479      108.0
16     undertone         104       52.0
17       unknown           0        0.0

In [ ]:
df_summary['win_rate'] = (df_summary['total_win']/df_summary['total_bids'])*100

In [ ]:
df_summary.sort_values('win_rate', ascending = False)

          bidder  total_bids  total_win   win_rate
16     undertone         104       52.0  50.000000
14         teads         700      323.0  46.142857
9     pulsepoint         191       71.0  37.172775
12  sharethrough         332      104.0  31.325301
6      onemobile        2726      759.0  27.842993
10     rhythmone         655      160.0  24.427481
1       appnexus         830      175.0  21.084337
2         criteo        3181      587.0  18.453317
0       33across         886      136.0  15.349887
3    emx_digital         393       56.0  14.249364
8       pubmatic        2335      255.0  10.920771
5       medianet        2556      253.0   9.898279
7          openx        1165       86.0   7.381974
15    triplelift        1479      108.0   7.302231
4             ix        3051      184.0   6.030810
11       rubicon         582       33.0   5.670103
13         sovrn         358       14.0   3.910615
17       unknown           0        0.0        NaN